name: sunmi_print_ticket
description: This is a printer product written by cudev
homepage: https://github.com/hueht21/SunmiPrintEasyTicket


version: 1.0.7

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: vn.lochv.b68
        pluginClass: PosPluginB68

