name: pos_ticket_b68
description: This is a printer product written by cudev
homepage: https://github.com/HVLoc/PosTicketB68

version: 1.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=3.10.5"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: vn.lochv.b68
        pluginClass: PosPluginB68

