name: sunmi_print_ticket
description: A new Flutter project.


version: 1.0.2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  sunmi_printer_plus: ^2.1.1
  intl: ^0.17.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.example.easy_ticket_b08
        pluginClass: SunmiPrinterPlugin

